### ISSUE TITLE
Permissions when used with docker compose

### ISSUE THREAD

**Issue by OBoudreaux** [jeffpiazza/derbynet#346]
I'm having a heck of a time with permissions when running via a docker-compose file. Setup page loads fine but I get an error that the derbynet directory isn't writable. I have the host data directory at 775 permissions with the same owner and group that the container is run with. I can jump in a console as user 1000 in the container and create files in the directory. Perplexed.
  
```
  derbynet:
    image: jeffpiazza/derbynet_server
    container_name: derbynet
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $DATADIR/db/derbynet:/var/lib/derbynet
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.derbynet-rtr.entrypoints=https"
      - "traefik.http.routers.derbynet-rtr.rule=Host(`$DERBYNET_SUBD.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.derbynet-rtr.middlewares=chain-authen@file"
     ## HTTP Services
      - "traefik.http.routers.derbynet-rtr.service=derbynet-svc"
      - "traefik.http.services.derbynet-svc.loadbalancer.server.port=80"

```

**Comment by OBoudreaux** [comment]
Weird, when I open a console in the container there is no www-data user
```
300e4ac716ce:/# cat /etc/passwd
root:x:0:0:root:/root:/bin/sh
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
nginx:x:100:101:nginx:/var/lib/nginx:/sbin/nologin
```

I've tried changing ownership of the data volume to nginx without success.

The image from mitchellriley/derbynet_server can write to the www-data owned volume and does have the www-data user inside Seems like he stopped updating with v6. Have there been substantial functional changes since then that would differ from the use documentation?

**Comment by OBoudreaux** [comment]
Have the same issue with the docker image (not docker compose) on a fresh install of Debian 12.  The repo packages work fine though so I'll just use those. Thanks!

**Comment by PorkChopExpress86** [comment]
Have you tried creating a docker volume and mounting as /var/lib/derbynet to the volume? Then, you can access the volume on Linux at /var/lib/docker/volumes/$DOCKER_VOLUME_NAME as root. I did this 2 years ago, and it still works great, even after migrating to another server.

**Comment by OBoudreaux** [comment]
I believe so...
```
     volumes:
      - $DATADIR/db/derbynet:/var/lib/derbynet
```

**Comment by PorkChopExpress86** [comment]
You are doing a bind to a directory on your Debian machine. You can create a docker volume with docker volume, create [volume name], or add volumes to the bottom and include the volume name. Compose will handle the creation of the volume, and it will be a persistent area that should have the correct permissions. To change the passwords, you need root access to /var/lib/docker/volumes/derbynet_data/_data/config-roles. You can use Nano or Vim to edit the file. 

```
  derbynet:
    image: jeffpiazza/derbynet_server
    container_name: derbynet
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - derbynet_data:/var/lib/derbynet
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.derbynet-rtr.entrypoints=https"
      - "traefik.http.routers.derbynet-rtr.rule=Host(`$DERBYNET_SUBD.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.derbynet-rtr.middlewares=chain-authen@file"
     ## HTTP Services
      - "traefik.http.routers.derbynet-rtr.service=derbynet-svc"
      - "traefik.http.services.derbynet-svc.loadbalancer.server.port=80"

volumes:
  derbynet_data:
```

**Comment by josiah47** [comment]
This works for me
##### compose.yaml
``` yaml 
name: derbynet
services:
  derbynet:
    image: jeffpiazza/derbynet_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /home/user/DerbyNet
        target: /var/lib/derbynet
    restart: unless-stopped
    environment:
      - PUID=100
      - PGID=101
```
Run command in directory with compose.yaml file
``` shell
docker compose up -d
```

**Comment by jamestford** [comment]
The PUID / PGID variables will not work for derbynet. They are specific variables used for the LinuxServer.io convention. The jeffpiazza/derbynet_server image will ignore them. Inside the container, PHP-FPM runs as user nginx (UID 100, GID 101 on Alpine). If the host directory is owned by UID 1000 then the nginx user can't write to it. Bind mounts inherit host permissions. Unlike Docker volumes, bind mounts don't adjust ownership.

Solutions:
Option A: Use a Docker Volume instead and have docker handle the permissions for you.  
Define a volume for the container
```
    volumes:
      - derbynet_data:/var/lib/derbynet  # replaces bind mount in service
```
Then define a top level volume outside of the container
```
volumes:                    # top-level volume definition
  derbynet_data:
```

Option B: Change the permissions of the data folder.
Fix host ownership	chown -R 100:101 /path/to/data (match container's nginx user)
Open permissions	chmod -R 777 /path/to/data (works but less secure as everything will be able to write to it)

**Comment by jamestford** [comment]
Here is an updated docker-compose.yml

```yaml
# DerbyNet Docker Compose Configuration
#
# BEFORE FIRST RUN:
#   1. Set the source volume path below to your data directory
#   2. Ensure the directory exists:
#      macOS/Linux: mkdir -p /path/to/your/data
#      Windows:     Create the folder in File Explorer
#
# Example paths:
#   macOS:   /Users/yourname/derbynet-data
#   Linux:   /home/yourname/derbynet-data
#   Windows: C:/Users/yourname/derbynet-data
#
# Linux permissions note:
#   The container runs as UID 100 (nginx). Either:
#   - Change ownership: sudo chown -R 100:101 /path/to/your/data
#   - Or use the Docker volume option at the bottom of this file
#
# Usage:
#   docker compose up -d              Start DerbyNet in background
#   docker compose down               Stop DerbyNet
#   docker compose logs -f            View logs (Ctrl+C to exit)
#   docker compose pull               Update to latest image
#   docker compose up -d --force-recreate   Apply changes after pull
#
# Access DerbyNet at: http://localhost or https://localhost

services:
  derbynet:
    image: jeffpiazza/derbynet_server:latest
    container_name: derbynet
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/your/data:/var/lib/derbynet  # <-- CHANGE /path/to/your/data to your data directory
    environment:
      - TZ=America/New_York
      - MAX_UPLOAD_SIZE=16M

# Linux alternative: Uncomment below and comment out the bind mount above
# to use a Docker-managed volume (avoids permission issues)
#    volumes:
#      - derbynet_data:/var/lib/derbynet  # replaces bind mount in service
#
#volumes:                    # top-level volume definition
#  derbynet_data:
```
